Update to `generated by rust-bindgen 0.69.2` in `native.rs`
Fixes the below CI failure:

> Error: Generated files are different, please regenerate with cargo run -p generator!
> diff --git a/ash/src/vk/native.rs b/ash/src/vk/native.rs
> index 223fb73..f28431a 100644
> --- a/ash/src/vk/native.rs
> +++ b/ash/src/vk/native.rs
> @@ -1,4 +1,4 @@
> -/* automatically generated by rust-bindgen 0.69.1 */
> +/* automatically generated by rust-bindgen 0.69.2 */
>
> #[repr(C)]
> #[derive(Copy, Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]